# Generated by Django 4.1.1 on 2022-09-18 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Variable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=60, unique=True)),
                ('value', models.CharField(blank=True, default='', max_length=250)),
            ],
            options={
                'db_table': 'variables',
                'ordering': ['-id'],
            },
        ),
    ]
